import argparse
import json
from datetime import datetime, timezone
from pathlib import Path


def encode_wikilink_target(value: str) -> str:
    # Keep target parse-safe for titles containing literal square brackets.
    # Use wikitext-safe entities so MediaWiki still resolves the real title.
    return value.replace("[", "&#91;").replace("]", "&#93;")


def build_wikilink(target: str, label: str | None = None) -> str:
    escaped_target = encode_wikilink_target(target)
    if label is None:
        return f"[[{escaped_target}]]"
    escaped_label = label.replace("[", "&#91;").replace("]", "&#93;")
    return f"[[{escaped_target}|{escaped_label}]]"


def load_page_titles(path: Path) -> list[str]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    pages = payload.get("pages", [])
    if not isinstance(pages, list):
        raise ValueError(f"Input JSON must contain 'pages' array: {path}")
    titles: list[str] = []
    for item in pages:
        if not isinstance(item, dict):
            continue
        title = str(item.get("title", "")).strip()
        if title:
            titles.append(title)
    return titles


def extract_prefixes(titles: list[str], root_prefix: str) -> list[str]:
    prefixes = set()
    normalized_root = root_prefix.rstrip("/") + "/"
    for title in titles:
        if not title.startswith(normalized_root):
            continue
        remainder = title[len(normalized_root) :]
        if "/" not in remainder:
            continue
        first_segment = remainder.split("/", 1)[0]
        if first_segment:
            prefixes.add(f"{normalized_root}{first_segment}/")
    return sorted(prefixes)


def build_wikitext(index_title: str, item_titles: list[str], npc_titles: list[str]) -> str:
    all_titles = sorted(set(item_titles + npc_titles))
    normalized_root = index_title.rstrip("/") + "/"
    prefixes = extract_prefixes(all_titles, normalized_root)
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines = [
        "==Bot sandbox index==",
        f"This page lists generated bot sandbox pages under '''{build_wikilink(index_title, index_title)}'''.",
        f"Last generated: {generated_at}",
        "",
        "===Quick links===",
        f"* {build_wikilink(f'Special:PrefixIndex/{normalized_root}', 'All sandbox pages')}",
    ]
    for prefix in prefixes:
        lines.append(f"* {build_wikilink(f'Special:PrefixIndex/{prefix}', prefix)}")
    lines.extend(
        [
            "",
            f"===Generated item pages ({len(item_titles)})===",
        ]
    )
    for title in sorted(item_titles):
        lines.append(f"* {build_wikilink(title, title)}")
    lines.extend(
        [
            "",
            f"===Generated npc pages ({len(npc_titles)})===",
        ]
    )
    for title in sorted(npc_titles):
        lines.append(f"* {build_wikilink(title, title)}")
    lines.extend(
        [
            "",
            "<!-- Generated by generate_sandbox_index_page.py -->",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate a sandbox index page payload listing all generated bot pages.")
    parser.add_argument("--items-pages", required=True, help="Path to pages.items.json")
    parser.add_argument("--npcs-pages", required=True, help="Path to pages.npcs.json")
    parser.add_argument("--output", required=True, help="Path to output pages JSON")
    parser.add_argument("--title", default="User:RSDWArchive", help="Title of the sandbox index page")
    parser.add_argument("--summary", default="Bot: update sandbox page index", help="Edit summary")
    args = parser.parse_args()

    items_titles = load_page_titles(Path(args.items_pages))
    npcs_titles = load_page_titles(Path(args.npcs_pages))
    text = build_wikitext(args.title, items_titles, npcs_titles)

    payload = {
        "generatedAtUtc": datetime.now(timezone.utc).isoformat(),
        "itemsPagesPath": str(Path(args.items_pages)),
        "npcsPagesPath": str(Path(args.npcs_pages)),
        "pages": [
            {
                "title": args.title,
                "text": text,
                "summary": args.summary,
                "meta": {
                    "itemPageCount": len(items_titles),
                    "npcPageCount": len(npcs_titles),
                },
            }
        ],
    }
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"[INFO] Wrote sandbox index payload to: {output_path}")
    print(f"[INFO] Indexed pages: items={len(items_titles)} npcs={len(npcs_titles)}")


if __name__ == "__main__":
    main()
